#%RAML 1.0
title: product-api
baseUri: http://localhost:8081/products
/products:
  get:
    description: to get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "product-id":"1234",
                "productName":"ArchanBose",
                "productProvider":"jhons",
                "productDescripton":"trialof mule components"
              }
            